### ISSUE TITLE
"PLINK/PSFTP" path is not relative to KeePass root 

### ISSUE THREAD

**Issue by kulmegil** [mitchcapper/KeePassSync#4]
The path is not relative to Keepass root folder, but the folder where plugin is compiled/cached.

Maybe it would simple be beneficial to resolve placeholders and field references (e.g. {APPDIR}) when reading field values.

![KeePassSync - no relative paths](https://github.com/mitchcapper/KeePassSync/assets/570575/f07e25b5-8655-42ec-b782-915f3e6f72df)

**Comment by mitchcapper** [comment]
Yeah I think because it was actually in place before plgx even and I myself only use compiled dlls so didn't notice.

I didn't add placeholder resolution but I did add a check against the keepass root (keepass.exe folder) now if it is not found elsewhere.   As you can (and probably should) already specify an absolute path this just makes the path finding a bit more logical for PLGX's.
